import '@fontsource/montserrat/400.css'
import '@fontsource/montserrat/500.css'
import '@fontsource/montserrat/600.css'
import '@fontsource/montserrat/700.css'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './app'
import '../styles/global.css'
import '../styles/appModal.css'
import '../styles/optionsPopup.css'
import '../styles/toolbarControls.css'
import '../styles/appSidebar.css'
import '../styles/dataTable.css'
import '../styles/astroChat.css'
import '../styles/login.css'
import '../styles/createWorkspace.css'
import '../styles/accessKeyVerified.css'
import '../styles/statusScreen.css'
import '../styles/workspaceCreated.css'
import '../styles/createPassword.css'
import '../styles/includeCompanyInformation.css'
import '../styles/attachExcelFile.css'
import '../styles/payment.css'
import '../styles/paymentLayout.css'
import '../styles/chargeExplanation.css'
import '../styles/spreadsheetExplanation.css'
import '../styles/loadingScreen.css'
import '../styles/setAddress.css'
import '../styles/notFound.css'
import '../styles/mainPositionScreen.css'
import '../styles/mainFormScreen.css'
import '../styles/mainEventScreen.css'
import '../styles/createEvent.css'
import '../styles/regulatoryStandardsDialog.css'
import '../styles/createForm.css'
import '../styles/editForm.css'
import '../styles/toggleSwitch.css'
import '../styles/workspaceSettings.css'
import '../styles/accountSettings.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter basename={import.meta.env.BASE_URL}>
      <App />
    </BrowserRouter>
  </StrictMode>,
)
